### ISSUE TITLE
TD-Shim spec doesn't mention device enumeration through the PCI bus

### ISSUE THREAD

**Issue by dimakuv** [confidential-containers/td-shim#100]
The TD-Shim spec has this section: https://github.com/confidential-containers/td-shim/blob/main/doc/tdshim_spec.md#device-reporting, saying:

> **Device Reporting**
> TD Shim does not report device to TD guest. The VMM may include the device in the boot parameter, or Flattened Device Tree (FDT).

From the other parts of the spec, I see that TD-Shim will provide the MCFG ACPI table to the guest kernel (if PCIe is exposed by the VMM). Also, TD-Shim will provide newly-defined Simple Static PCI Routing Table (SPRT) ACPI table to the guest kernel. Finally, combining the info from these two tables (MCFG and SPRT), we can examine the whole PCI configuration space and detect all devices, as well as their IRQ mappings.

So I'm confused as to why there is a sentence on `The VMM may include the device in the boot parameter, or Flattened Device Tree (FDT)`? And why is there no mention of the PCI bus?

**Comment by jiangliu** [comment]
In addition to PCI bus, there are some other type of virtual buses for micro-vm.
For example, dragonball and firecracker microvm uses an virtual MMIO bus instead of PCI buses in some scenarios.

**Comment by dimakuv** [comment]
Thanks for the reply! I understand the point about virtio-mmio bus.

But I'm still confused about the security guarantees of TD-Shim. So TD-Shim doesn't report any devices to the TD guest -- which I guess means that TD-Shim doesn't provide any *trusted*, TD-hardened device interface to the TD guest.

Instead, the TD guest must collect the available devices itself, based on the information from the VMM passed as-is from TD-Shim to the TD guest. So the TD guest must be aware that the VMM may lie about the devices and their characteristics. TD-Shim provides no guarantees here, other than adding the VMM guest-boot parameters  to the `RTMR[1]` TD measurement register. Is my understanding correct? The TD-Shim firmware doesn't give any guarantees to the TD guest regarding the devices?

**Comment by jyao1** [comment]
Your understanding is correct.
TD-Shim cannot provide any trusted device to TD guest. In whole TDX 1.0 architecture, there is no such guarantee.

TdShim's job is to do minimal thing to boot the system. Since TdShim does not requires the device, there is no need to add device driver. The input from VMM is recorded to RTMR, e.g. ACPI table is recorded. If it contains a device, then the device info is recorded in RTMR.  But TDShim will not verify if the device is required, or if the device behaves correctly.

**Comment by dimakuv** [comment]
Thank you @jyao1! Now I get it.
