### ISSUE TITLE
[Bug] Should do sanity check for cfv before using it

### ISSUE THREAD

**Issue by liuw1** [confidential-containers/td-shim#108]
td-shim/src/bin/td-shim/main.rs : line 471

#[cfg(feature = "secure-boot")]
    {
        let cfv = memslice::get_mem_slice(memslice::SliceType::Config);
        let verifier = verifier::PayloadVerifier::new(payload, cfv);
        if let Ok(verifier) = &verifier {
            td_event_log.create_event_log(
                4,
                EV_PLATFORM_CONFIG_FLAGS,
                b"td payload",
                verifier::PayloadVerifier::get_trust_anchor(cfv).unwrap(),
            );
            verifier.verify().expect("Verification fails");
            td_event_log.create_event_log(4, EV_PLATFORM_CONFIG_FLAGS, b"td payload", payload);
            td_event_log.create_event_log(
                4,
                EV_PLATFORM_CONFIG_FLAGS,
                b"td payload svn",
                &u64::to_le_bytes(verifier.get_payload_svn()),
            );

**Comment by gaojiaqi7** [comment]
https://github.com/confidential-containers/td-shim/commit/65e1c6e5b52204abd292d925d5591d9c79e671ac
