### ISSUE TITLE
build script should check dependencies and fail early

### ISSUE THREAD

**Issue by jodh-intel** [confidential-containers/td-shim#110]
Building the shim is currently somewhat awkward since you need:

- clang ([GCC won't work](https://github.com/confidential-containers/td-shim/issues/109)).
- nasm
- `cargo xbuild`

Admittedly, this _is_ documented in https://github.com/confidential-containers/td-shim/blob/staging/README.md, but we should make it easier for users by checking for the expected commands in `build.rs` so that the build can fail early (rather than letting it chug on and die in flames at some later stage).

Related:

- https://github.com/confidential-containers/td-shim/pull/2#issuecomment-977991422
- https://github.com/confidential-containers/td-shim/pull/2#discussion_r759137136

**Comment by jyao1** [comment]
@jodh-intel, can you take this and propose a patch?

**Comment by jodh-intel** [comment]
Yes, I can look at this, but I don't have privs to assign this issue to myself.

@sameo - could you possibly assign to me or grant me those privs?
