### ISSUE TITLE
Latest version "0.14.7" of crate x86_64 fails to build

### ISSUE THREAD

**Issue by gaojiaqi7** [confidential-containers/td-shim#13]
Solve the problem temporarily by fixing crate version to "0.14.6": https://github.com/confidential-containers/td-shim/pull/12

error[E0658]: panicking in constant functions is unstable
   --> C:\Users\gaojiaqi\.cargo\registry\src\github.com-1ecc6299db9ec823\x86_64-0.14.7\src\addr.rs:547:5
    |
547 |     assert!(align.is_power_of_two(), "`align` must be a power of two");
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #51999 <https://github.com/rust-lang/rust/issues/51999> for more information
    = help: add `#![feature(const_panic)]` to the crate attributes to enable
    = note: this error originates in the macro `$crate::panic::panic_2015` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by jyao1** [comment]
https://github.com/confidential-containers/td-shim/pull/12 is work-around to pass build.

Need a solution to use latest crate.

**Comment by gaojiaqi7** [comment]
Lock the version of crate bootloader to avoid CI issue.

**Comment by gaojiaqi7** [comment]
Rust toolchain version has been updated,  latest x86_64 can be used now: https://github.com/confidential-containers/td-shim/commit/c3061df2fef0fcc2b655c83b24b27bb44092b1fb
