### ISSUE TITLE
TD-Shim needs to map all of the memory reported by VMM

### ISSUE THREAD

**Issue by gaojiaqi7** [confidential-containers/td-shim#131]
TD-Shim constructs the page table but only maps 0-36GB at now

**Comment by jyao1** [comment]
I think all memory only covers private memory (guest physical memory).
MMIO should not be included, because MMIO access is via TDVMCALL.

**Comment by gaojiaqi7** [comment]
Fixed by https://github.com/confidential-containers/td-shim/commit/5d05b841028353a7b4d0bab605819367349b005d
