### ISSUE TITLE
CI: Fails to build PE format payload

### ISSUE THREAD

**Issue by gaojiaqi7** [confidential-containers/td-shim#134]
running "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "--target=x86_64-pc-windows-msvc" "-I" "include" "-Wall" "-Wextra" "/GS" "/Gy" "/EHsc" "/GR-" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Zc:rvalueCast" "/sdl" "/Wall" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/wd5045" "/Od" "/RTCsu" "/WX" "-c" "/FoD:\\a\\td-shim\\td-shim\\target\\debug\\build\\ring-917f19b5a6b6e7a0\\out\\aes_nohw.obj" "crypto/fipsmodule/aes/aes_nohw.c"
  clang: error: no such file or directory: '/GS'
  clang: error: no such file or directory: '/Gy'
  clang: error: no such file or directory: '/EHsc'
  clang: error: no such file or directory: '/GR-'
  clang: error: no such file or directory: '/Zc:wchar_t'
  clang: error: no such file or directory: '/Zc:forScope'
  clang: error: no such file or directory: '/Zc:inline'
  clang: error: no such file or directory: '/Zc:rvalueCast'
  clang: error: no such file or directory: '/sdl'
  clang: error: no such file or directory: '/Wall'; did you mean '-Wall'?
  clang: error: no such file or directory: '/wd4127'
  clang: error: no such file or directory: '/wd4464'
  clang: error: no such file or directory: '/wd4514'
  clang: error: no such file or directory: '/wd4710'
  clang: error: no such file or directory: '/wd4711'
  clang: error: no such file or directory: '/wd4820'
  clang: error: no such file or directory: '/wd5045'
  clang: error: no such file or directory: '/Od'
  clang: error: no such file or directory: '/RTCsu'
  clang: error: no such file or directory: '/WX'
  clang: error: no such file or directory: '/FoD:\a\td-shim\td-shim\target\debug\build\ring-917f19b5a6b6e7a0\out\aes_nohw.obj'
  thread 'main' panicked at 'execution failed', C:\Users\runneradmin\.cargo\git\checkouts\ring-1836a5bf48f90a2a\3e04208\build.rs:663:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Warning: error: build failed
Error: Process completed with exit code 1.

**Comment by haowqs** [comment]
I want to solve this issue.
