### ISSUE TITLE
Move more code from staging branch into main branch

### ISSUE THREAD

**Issue by jiangliu** [confidential-containers/td-shim#137]
Currently we are facing the trouble of developing on two branches concurrently. So it would be great to speed up the progress to merge code from staging into main branch. To achieve that, we may:
- submit all merged code applicable to the main branch into the main branch
- td-loader
- td-shim library
- td-shim binary
- td-payload binary
- td-shim-tools (non-secure boot parts)
- integration tests
- secure boot related td-shim-tools and docs
- fuzz tests

**Comment by jyao1** [comment]
Good step by step.

**Comment by jyao1** [comment]
done
