### ISSUE TITLE
[Bug] td-shim should support reproducible build

### ISSUE THREAD

**Issue by liuw1** [confidential-containers/td-shim#256]
There are some differences between 2 times build with same code base. Currently td-shim does not support reproducible build.

![image](https://user-images.githubusercontent.com/35357095/166177999-30975526-572b-44bd-92eb-33c4b102335b.png)

**Comment by jiangliu** [comment]
It's really import to get this fixed, reproducible build is fatal for CC:)
Thanks for working this!

**Comment by jyao1** [comment]
Some investigation result from @longlongyang.

Elements break reproducible build (x86_64-unknown-uefi + target x86_64-unknown-none)
1.	Debug related sections (PE + ELF)
2.	Code base path like \home\long\rust-tpa\xxx\xxx.rs (PE + ELF)
3.	CARGO_HOME like \home\long\.cargo\xxx\xxx.rs (PE + ELF)
4.	RUSTUP_HOME like \home\long\.rustup\xxx\xxx.rs (PE + ELF)
5.	TimeDateStamp field in COFF file header (PE only)

Solution:
1.	Use `strip = "symbols"` option to `[profile.release]`
2.	Use `strip = "symbols"` option to `[profile.release]`
3.	Use a post-build tool to zero CARGO_HOME string
4.	Use a post-build tool to zero RUSTUP_HOME string
5.	Use a post-build tool to zero TimeDateStamp for PE

NOTE: 3 and 4 may be resolved directly after rust-lang RFC 3127. It is temp solution before RFC is implemented.

**Comment by longlongyang** [comment]
I would like to take this issue.

**Comment by jyao1** [comment]
After more investigation, we notice that Use strip = "symbols" option to [profile.release] is not stable.

It is just added in latest 1.59 version - https://github.com/confidential-containers/td-shim/issues/269.

And it causes weird issue - https://github.com/confidential-containers/td-shim/issues/272

As such, I think we need use post-build tool to resolve 1 and 2 as well.

After the tool is stable, we can use strip again.
