### ISSUE TITLE
[Bug] Total memory size calculated with memory map table is not equal with expected size

### ISSUE THREAD

**Issue by liuw1** [confidential-containers/td-shim#261]
Run test case memorymap001 will find that the total memory size calculated with memory map table is not equal with expected size.

Log:
```
INFO - [Test: memorymap001]
ERROR - Mismatch memory size: 40004000, expected: 40000000
INFO - [Test: memorymap001] - Fail
```

**Comment by gaojiaqi7** [comment]
Solved by https://github.com/confidential-containers/td-shim/commit/60e7664794c0e1bf3f42a82eac052ca1bac84967
