### ISSUE TITLE
consider support lazy-accept memory for boot performance

### ISSUE THREAD

**Issue by jyao1** [confidential-containers/td-shim#275]
The unaccepted memory type definition:

1) UEFI: https://github.com/chris-oo/mu_basecore/blob/personal/cho/unaccepted-memory-type/Unaccepted%20Memory%20UEFI%20ECR.md

2) PI: https://github.com/chris-oo/mu_basecore/blob/personal/cho/unaccepted-memory-type/Unaccepted%20Memory%20PI%20ECR.md

3) ACPI: https://github.com/jyao1/mu_basecore/blob/unaccepted-memory-type/Unaccepted%20Memory%20ACPI%20ECR.md

All proposal will be in UEFI/PI/ACPI specification.

**Comment by jyao1** [comment]
yes, please.

**Comment by gaojiaqi7** [comment]
Can be closed by https://github.com/confidential-containers/td-shim/commit/ab94a09cfeb9d3ce533e2563bf1514ede16abc70
