### ISSUE TITLE
Move function "secure_boot_verify_payload" from bin to a generic package

### ISSUE THREAD

**Issue by liuw1** [confidential-containers/td-shim#278]
Since the function "secure_boot_verify_payload" will read CFV and pyaload, the data is untrusted. So we need to get the interface of the function and verify the code security with fuzzing.

**Comment by gaojiaqi7** [comment]
Close with https://github.com/confidential-containers/td-shim/commit/1a78d73c66bb409fd9a663174f5bab4cbf4a8d2e
