### ISSUE TITLE
use sha2 and/or openssl/mbedtls to replace ring

### ISSUE THREAD

**Issue by jyao1** [confidential-containers/td-shim#294]
Current td-shim need use SHA384 to calculate the MR extend.

Since ring upstream is blocked, we should use sha2 to replace ring.

Rust crypto provides https://github.com/RustCrypto/hashes. SHA384 is available in https://crates.io/crates/sha2

**Comment by gaojiaqi7** [comment]
We still use ring to verify the payload signature, is there a substitute for this?

**Comment by jyao1** [comment]
That is secure boot specific, right? Let's first put ring to secure-boot feature.

**Comment by jyao1** [comment]
For secure boot, we may consider https://crates.io/crates/openssl

**Comment by jodh-intel** [comment]
Related: https://github.com/confidential-containers/community/issues/44.

**Comment by ariel-adam** [comment]
@jyao1 is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by dcmiddle** [comment]
@jyao1 can you clarify:
> Since ring upstream is blocked, we should use sha2 to replace ring.

Is there a blocked issue or something we can track?

**Comment by dcmiddle** [comment]
@jyao1 is this issue resolved now via #428?
