### ISSUE TITLE
need clear more debug info in PE image

### ISSUE THREAD

**Issue by jyao1** [confidential-containers/td-shim#302]
1) The `TimeDateStamp` in debug directory entry is not cleared.

REF: https://docs.microsoft.com/en-us/windows/win32/debug/pe-format

2) The `Guid` in CodeView Debug Directory Entry is not cleared

REF: https://github.com/dotnet/runtime/blob/main/docs/design/specs/PE-COFF.md

Overall, please refer to `ZeroDebugData()` in https://github.com/tianocore/edk2/blob/master/BaseTools/Source/C/GenFw/GenFw.c

**Comment by longlongyang** [comment]
Awesome findings and reference! I'll take it.
