### ISSUE TITLE
Remove build.rs from rust-td-layout

### ISSUE THREAD

**Issue by jiangliu** [confidential-containers/td-shim#33]
The `build.rs` is used to generate build time and runtime constants, it's a little over-complex. Should we remove the build.rs and maintain `build_time.rs` and `runtime.rs` directly?

**Comment by jiangliu** [comment]
Think about it again, I still think we should split out the build.rs, will give it a try.

**Comment by xiaoyuxlu** [comment]
Good idea.
I think this's good. It will also reduce dependencies during compilation. 
Keep it simple !!!
and Thanks for your contribution.
