### ISSUE TITLE
Consider to update VMM/TD-Shim memory interface to align with TDVF

### ISSUE THREAD

**Issue by gaojiaqi7** [confidential-containers/td-shim#336]
In the latest version TDVF spec, the private memory is reported as EFI_REOURCE_SYSTEM_MEMORY, and unaccepted memory is reported as EFI_REOURCE_SYSTEM_UNACCEPTED, which is not align with the description in [TD Shim spec](
https://github.com/confidential-containers/td-shim/blob/main/doc/tdshim_spec.md#memory-information).

Considering the compatibility with upstream version of QEMU/TDVF, we may need to update the interface.
TDVF design guide: https://cdrdv2.intel.com/v1/dl/getContent/733585
QEMU upstream: https://github.com/intel/qemu-tdx/blob/tdx-upstream-wip/hw/i386/tdvf-hob.c#L79

**Comment by jyao1** [comment]
OK.

**Comment by gaojiaqi7** [comment]
Completed by https://github.com/confidential-containers/td-shim/commit/154c7d7a5bcadee22ac95604cbcdea9cae4ec6d2
