### ISSUE TITLE
Build fails due to the crate `libc` update

### ISSUE THREAD

**Issue by gaojiaqi7** [confidential-containers/td-shim#356]

**Comment by gaojiaqi7** [comment]
Can be solved by
 - updating rust version: https://github.com/confidential-containers/td-shim/pull/354 or
 - locking `libc` version in td-shim: https://github.com/confidential-containers/td-shim/pull/355

**Comment by jyao1** [comment]
both CI failed?

**Comment by gaojiaqi7** [comment]
It seems installation of cargo-xbuild will fail because it relies on libc too, if we only lock the `libc` version

**Comment by fidencio** [comment]
@jyao1, I've noticed the same failure when trying to build 5f62a0e367b1845a54e534d103ed4a697a599ac3 as part of the Confidential Containers effort.
