### ISSUE TITLE
[MIRAI] Potential arithmetic overflow in td-shim/memory.rs

### ISSUE THREAD

**Issue by liuw1** [confidential-containers/td-shim#376]
warning: possible attempt to add with overflow
   --> td-shim/src/bin/td-shim/memory.rs:284:21
    |
284 |                     new.physical_start += to_be_accepted;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: possible attempt to subtract with overflow
   --> td-shim/src/bin/td-shim/memory.rs:285:21
    |
285 |                     new.resource_length -= to_be_accepted;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: possible attempt to add with overflow
   --> td-shim/src/bin/td-shim/memory.rs:286:38
    |
286 |                     resources.insert(idx + 1, new);
    |                                      ^^^^^^^

warning: possible attempt to subtract with overflow
   --> td-shim/src/bin/td-shim/memory.rs:298:21
    |
298 |                     to_be_accepted -= size;
    |                     ^^^^^^^^^^^^^^^^^^^^^^

**Comment by liuw1** [comment]
Please assign to jiaqi

**Comment by gaojiaqi7** [comment]
> warning: possible attempt to add with overflow --> td-shim/src/bin/td-shim/memory.rs:284:21 | 284 | new.physical_start += to_be_accepted; | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
This can be ensured by checking the validity of the resource hobs

> warning: possible attempt to subtract with overflow --> td-shim/src/bin/td-shim/memory.rs:285:21 | 285 | new.resource_length -= to_be_accepted; | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
the `to_be_accepted` here is less than or equal to the `resource_length`

> warning: possible attempt to add with overflow --> td-shim/src/bin/td-shim/memory.rs:286:38 | 286 | resources.insert(idx + 1, new); | ^^^^^^^
> 
It is impossible for `idx` to overflow since we don't so much memory to hold the `usize::MAX * size_of::<ResourceDescription>()`

> warning: possible attempt to subtract with overflow --> td-shim/src/bin/td-shim/memory.rs:298:21 | 298 | to_be_accepted -= size; | ^^^^^^^^^^^^^^^^^^^^^^
>
the `size` here is less than or equal to the `to_be_accepted `

**Comment by liuw1** [comment]
@gaojiaqi7 
warning: possible attempt to add with overflow --> td-shim/src/bin/td-shim/memory.rs:284:21 | 284 | new.physical_start += to_be_accepted; | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

If the feature is not "lazy-accept", td_be_accepted = u64::MAX. Line 321 may overflow.
https://github.com/confidential-containers/td-shim/blob/553e3e6b3886a56a05decbbab37561da2fc5c534/td-shim/src/bin/td-shim/memory.rs#L311

**Comment by gaojiaqi7** [comment]
It should not go into line 321

**Comment by liuw1** [comment]
Sorry, I misunderstood it. The fix is OK. So close it.
