### ISSUE TITLE
[MIRAI] Potential arithmetic overflow in td-layout

### ISSUE THREAD

**Issue by liuw1** [confidential-containers/td-shim#396]
warning: possible attempt to subtract with overflow
  --> td-layout/src/lib.rs:99:13
   |
99 |             current_base -= TD_PAYLOAD_UNACCEPTED_MEMORY_BITMAP_SIZE as u64;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: possible attempt to add with overflow
   --> td-layout/src/metadata.rs:228:21
    |
228 |                     bfv_cnt += 1;
    |                     ^^^^^^^^^^^^

warning: possible attempt to add with overflow
   --> td-layout/src/metadata.rs:268:21
    |
268 |                     hob_cnt += 1;
    |                     ^^^^^^^^^^^^

warning: possible attempt to add with overflow
   --> td-layout/src/metadata.rs:312:21
    |
312 |                     perm_mem_cnt += 1;
    |                     ^^^^^^^^^^^^^^^^^

warning: possible attempt to add with overflow
   --> td-layout/src/metadata.rs:333:21
    |
333 |                     payload_cnt += 1;
    |                     ^^^^^^^^^^^^^^^^

warning: possible attempt to add with overflow
   --> td-layout/src/metadata.rs:353:21
    |
353 |                     payload_param_cnt += 1;
    |                     ^^^

**Comment by gaojiaqi7** [comment]
> --> td-layout/src/lib.rs:99:13
> |
> 99 | current_base -= TD_PAYLOAD_UNACCEPTED_MEMORY_BITMAP_SIZE as u64;
> | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

hi, can you help to try with the https://github.com/confidential-containers/td-shim/pull/397 to see if this still a warning?
