### ISSUE TITLE
Move event log out from td-shim and enhance its API

### ISSUE THREAD

**Issue by gaojiaqi7** [confidential-containers/td-shim#405]

**Comment by jyao1** [comment]
Please add more detail on why this is needed.
This description just tells what, but no clue on why.

**Comment by gaojiaqi7** [comment]
It is moved out from `td-shim` crate to facilitate other programs to use it to replay or query the event log, including `EventlogWriter`, `EventlogReader` and some TCG definitions

**Comment by gaojiaqi7** [comment]
Completed by https://github.com/confidential-containers/td-shim/pull/406
