### ISSUE TITLE
Status track for merging the staging branch into the main branch

### ISSUE THREAD

**Issue by jiangliu** [confidential-containers/td-shim#42]
As the td-shim has been merged into the staging branch, we need a plan to eventually merge it into main branch. Let's get it done piece by piece. So a checklist table is maintained here to track the status.

Approvers may review and approve the project by components, and mark a component as ready for merging in the following table. One all components has received enough approves, the staging branch will be merged into the main branch. Anyone who is willing to help the migration process may add himself/herself into the below table as approvers.

| Approver | Status | @c3d  | @jiangliu | @jyao1  | @sameo | 
| --- | --- | --- | --- | --- | --- |
| Build System | [Merged](https://github.com/confidential-containers/td-shim/pull/44) | Y | S | Y |  |
| devtools/dev-container | [Merged](https://github.com/confidential-containers/td-shim/pull/50) | Y | S | | Y|
| devtools/td-benchmark |
| devtools/td-layout-config | [Merged](https://github.com/confidential-containers/td-shim/pull/51) | Y | S |  Y | | 
| devtools/test-runner-server/client | [Merged](https://github.com/confidential-containers/td-shim/pull/58) | | S | Y | |
| td-exception |
| td-layout | [Merged](https://github.com/confidential-containers/td-shim/pull/51) | Y | S | Y| |
| td-paging | [Merged](https://github.com/confidential-containers/td-shim/pull/66) | | S | Y | |
| td-payload |
| td-shim |
| td-shim-enroll-key |
| td-shim-ld |
| td-shim-sign-payload |
| tdx-tdcall | [Reviewing](https://github.com/confidential-containers/td-shim/pull/72) | | S | Y | |
| td-uefi-pi | [Reviewing](https://github.com/confidential-containers/td-shim/pull/83) | | S |

**Comment by c3d** [comment]
@jiangliu Thanks a lot for doing that. What about documentation / slides? Those are easier to merge first, no?

**Comment by jiangliu** [comment]
> @jiangliu Thanks a lot for doing that. What about documentation / slides? Those are easier to merge first, no?

Yes, let's move along that way.
It would be great to eventually merge the staging branch into the main branch, so we could keep the development history.

**Comment by jyao1** [comment]
staging branch is merged to main. Close this one.
