### ISSUE TITLE
no-std code coverage collection doesn't work

### ISSUE THREAD

**Issue by liuw1** [confidential-containers/td-shim#494]
grcov --branch --guess-directory-when-missing --ignore-not-existing --llvm --binary-path target/release/final-elf.bin --source-dir ./ --output-type html --output-path target/release/coverage test.profraw
warning: /home/liuwei/td-shim/test.profraw: unrecognized instrumentation profile encoding format
error: no profile can be merged
01:30:04 [ERROR] Error while executing llvm tools: Failure while running "/home/liuwei/.rustup/toolchains/nightly-2022-05-15-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata" "merge" "-f" "-" "-sparse" "-o" "/tmp/.tmpUGgS7t/1/grcov.profdata"

**Comment by jyao1** [comment]
Need CI as well.
