### ISSUE TITLE
evaluate the aws-lc-rs as replacement for ring

### ISSUE THREAD

**Issue by jyao1** [confidential-containers/td-shim#562]
reference: https://github.com/awslabs/aws-lc-rs

**Comment by gaojiaqi7** [comment]
`aws-lc-rs` does not support `no_std`: https://github.com/awslabs/aws-lc-rs/blob/main/aws-lc-rs/src/lib.rs#L93-L96

**Comment by jyao1** [comment]
See issue 114 there.
