### ISSUE TITLE
Are private accepted memory pages zeroed out?

### ISSUE THREAD

**Issue by dimakuv** [confidential-containers/td-shim#563]
The TD-Shim spec doesn't mention whether all private accepted memory pages in a TD are zeroed out initially? I assume yes (and probably it's the TDX hardware that does it/mandates it?). But I'd like to know for sure.

**Comment by dimakuv** [comment]
According to my experiments, yes, all private accepted memory pages are zeroed out.

**Comment by jyao1** [comment]
This is mentioned in TDX-module spec.

```
22.3.2. TDG.MEM.PAGE.ACCEPT Leaf
Accept a pending private page, and initialize the page to all-0 using the TD ephemeral private key.
```
