### ISSUE TITLE
CI: fuzz may fail

### ISSUE THREAD

**Issue by gaojiaqi7** [confidential-containers/td-shim#595]
CI output:

Test Case: td-uefi-pi - afl_payload_parser fail
~/work/td-shim/td-shim
~/work/td-shim/td-shim/td-shim ~/work/td-shim/td-shim
Test Case: td-shim - afl_secure_boot_cfv fail
Test Case: td-shim - afl_secure_boot_payload fail

**Comment by liuw1** [comment]
I will take this task

**Comment by jyao1** [comment]
if the failure is caused by "no enough CPU core", then can we reduce the required CPU core number?

**Comment by liuw1** [comment]
For fuzzing CI, we only need 1 cpu core in same period. 

So it's random issue, we can not predict when the cpus will be locked by other tasks. I tried to use command `afl-gotcpu` to check cpu status before run AFL test case. But it doesn't work.

I will keep to find solutions.
