### ISSUE TITLE
TD-Shim fuzzing

### ISSUE THREAD

**Issue by dimakuv** [confidential-containers/td-shim#624]
As I understand it, the TD-Shim fuzzing logic is implemented via libfuzzer and **at the level of separate crates** to test their **functional (benign) execution**.

For example, there is a fuzz test for TD-Loader's ELF payload parsing logic:
- https://github.com/confidential-containers/td-shim/blob/678aa9886b7962edd3efe35db0c612a086eb2e05/td-loader/fuzz/fuzz_targets/elf.rs#L9
- https://github.com/confidential-containers/td-shim/blob/678aa9886b7962edd3efe35db0c612a086eb2e05/td-loader/fuzz/fuzz_targets/fuzzlib.rs#L8

While very useful, this fuzzing is purely functional and **not TDX attack surface related**. For example, I think there are no specific fuzzing tests to exercise e.g. untrusted MMIO inputs?

Is my understanding correct that current fuzzing targets **benign executions**, and not **TDX attacks**?

**Comment by dimakuv** [comment]
> We have TDX attack surface related fuzzing test, like TD Hob

Thanks, yes, that's one attack surface.

But I'm more interested in **runtime** attack vectors, like malicious inputs from MMIO reads, Port IO reads, CPUID leaves, MSR reads, etc.

> Cause td-shim has no tdx_MMIO_read operation, so you can not find the specific fuzzing test case in td shim repo.

Yes, you are right, sorry for a bad example. There are indeed no MMIO reads in TD-Shim code.

But what about fuzzing the other input points (VMCALLs basically)? I don't see fuzzing for these modules:
- https://github.com/confidential-containers/td-shim/blob/678aa9886b7962edd3efe35db0c612a086eb2e05/tdx-tdcall/src/tdx.rs
- https://github.com/confidential-containers/td-shim/blob/bf33d12298eb79daca6540ddf622bdf984ef681c/td-exception/src/interrupt.rs

**Comment by liuw1** [comment]
Agree with you, the crate tdx-tdcall and td-exception provide interfaces, if any service payload uses VMCALLs to get some data(untrusted), we need add fuzzing test case to cover. 
For example, we added virtio fuzzing test case in migtd.
https://github.com/intel/MigTD/blob/main/src/devices/virtio/fuzz/fuzz_targets/afl-virtio.rs

**Comment by dimakuv** [comment]
Ok, thanks for the link.

Still not exactly what I was looking for (it's more like a unit test with a fuzz input to the virtio device), but I understand the fuzzing strategy of these TD-Shim and MigTD projects now. Thank you for your replies!
