### ISSUE TITLE
Support for TDX Connect archicture

### ISSUE THREAD

**Issue by dimakuv** [confidential-containers/td-shim#652]
Is there any plan to support the TDX Connect architecture?

Or maybe there's nothing to be done at the TD-Shim level, and the OS kernel (e.g. Linux) is supposed to initiate a trusted connection with a TDISP-capable device?

**Comment by jyao1** [comment]
No special support in TDVF/TD-Shim is needed for TDX Connect.
Close it.

If you find some thing needed, please file an issue with specific requirement.
