### ISSUE TITLE
Add more doc for tdx-tdcall

### ISSUE THREAD

**Issue by jiangliu** [confidential-containers/td-shim#69]
It would be helpful to quote some spec documentation in the tdx-tdcall crate, so it would be easier to understand the code.

**Comment by jyao1** [comment]
All TD-CALLs are documented at [TDX Module 1.0 EAS](https://software.intel.com/content/dam/develop/external/us/en/documents/tdx-module-1.0-public-spec-v0.931.pdf)

All TD-VMCALLs are documented at [GHCI 1.0](https://www.intel.com/content/dam/develop/external/us/en/documents/intel-tdx-guest-hypervisor-communication-interface-1.0-344426-002.pdf)

**Comment by gaojiaqi7** [comment]
Documentation has been added to 'tdx-tdcall' crate
