### ISSUE TITLE
remove hardcoded MAX_WORKING_AP_COUNT

### ISSUE THREAD

**Issue by jyao1** [confidential-containers/td-shim#705]
https://github.com/confidential-containers/td-shim/blob/main/td-shim/src/bin/td-shim/td/tdx_mailbox.rs#L19

What happen if VMM injects more CPUs than MAX_WORKING_AP_COUNT ?

**Comment by gaojiaqi7** [comment]
This sets a maximum numbers of APs that are used to accept memory and is intentional. If VMM injects more CPUs than MAX_WORKING_AP_COUNT, only `MAX_WORKING_AP_COUNT` CPUs will be waked up to do the works they are assigned.

**Comment by jyao1** [comment]
If there is no impact to the OS ACPI table, then it is OK.
