### ISSUE TITLE
Upstream TDCALL library as crate to crates.io

### ISSUE THREAD

**Issue by vijaydhanraj** [confidential-containers/td-shim#706]
We are enabling TD partitioning support in SVSM (https://github.com/coconut-svsm/svsm). Our current implementation uses tdx-tdcall library from the TD-shim project.  But rather than do copy-paste-modify, request is to upstream TDCALL library to crates.io so that TD partitioning code can directly refer to it from crates.io.

- What interface is needed – the APIs to upload to Crates.io
    - We use most of TDCALL functions as part of tdx-tdcall folder, so the request is to upstream all the pub interfaces that are part of it.

**Comment by jyao1** [comment]
See the first version at https://crates.io/crates/tdx-tdcall
