### ISSUE TITLE
Add new TDCALL functions to support TD partitioning

### ISSUE THREAD

**Issue by vijaydhanraj** [confidential-containers/td-shim#707]
Once https://github.com/confidential-containers/td-shim/issues/706 is done the next step would be to add new TDCALL functions to support TD partitioning. The following new TDCALLs may be required.

- New APIs:
    - Wrapper to `tdcall_accept_page` accept a memory range ( `td_accept_memory` that takes start address and len of address range to be accepted).
    - Add tdcall_vm_read/write to access TD-scope meta field of a TD.
    - Add tdcall_vp_read/write is to access vCPU-scope meta field of a TD.
    - Add tdcall_vp_invept/invvpid to provide SEPT flushing support.
    - Add tdcall_vp_enter support.
    - Add tdcall to support memory attribute write.

**Comment by jyao1** [comment]
@vijaydhanraj, Could you please split the requirement to 3 different categories: 1. Change existing, 2. Clean up, 3. Add new ones?

Usually, we do not put so many request into one issue. The different task be assigned to different owner, with different time.

**Comment by vijaydhanraj** [comment]
Sure, will do accordingly. This issue, I will keep for adding new TDCALLs as the title says and will create two other issues for existing changes and cleanup.

**Comment by vijaydhanraj** [comment]
Created https://github.com/confidential-containers/td-shim/issues/708 for changing existing APIs and created https://github.com/confidential-containers/td-shim/issues/709 for general clean-ups.
