### ISSUE TITLE
Wrong IPL FV header checksum?

### ISSUE THREAD

**Issue by dingelish** [confidential-containers/td-shim#729]
Hi there,

I'm trying to understand TD-shim. I cannot make sense of the hardcoded checksum at [td-shim-tools/src/linker.rs#L158](https://github.com/confidential-containers/td-shim/blob/main/td-shim-tools/src/linker.rs#L158)

```
tdx_ipl_fv_header.fv_header.checksum = 0x3d21;
```

I looked at [UEFI PI spec](https://uefi.org/sites/default/files/resources/PI_Spec_1_6.pdf). The `EFI_FIRMWARE_VOLUME_HEADER` is defined as

```
typedef struct {
    UINT8 ZeroVector[16];
    EFI_GUID FileSystemGuid;
    UINT64 FvLength;
    UINT32 Signature;
    EFI_FVB_ATTRIBUTES_2 Attributes;
    UINT16 HeaderLength;
    UINT16 Checksum;
    UINT16 ExtHeaderOffset;
    UINT8 Reserved[1];
    UINT8 Revision;
    EFI_FV_BLOCK_MAP BlockMap[];
} EFI_FIRMWARE_VOLUME_HEADER;
```

I built the TD-shim firmware using default command (RV + IPL + linux kernel boot) and here's the dump of the FV header
```
00caf000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00caf010: 78e5 8c8c 3d8a 1c4f 9935 8961 85c3 2dd3  x...=..O.5.a..-.
00caf020: 0010 3500 0000 0000 5f46 5648 fff6 0400  ..5....._FVH....
00caf030: 4800 213d 6000 0002 5103 0000 0010 0000  H.!=`...Q.......
00caf040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```
The header length is `0x48 = 72` . This means it's a 56-byte header plus a 2x8=16-byte blockmap. According to the UEFI PI standard, the sum of the 72-byte header should be 0. However, using the `sum16` function on this header I got a value of `0x6238`. I wonder if the hardcoded checksum is wrong, or my understanding is incorrect. If I'm understanding correctly, the checksum should be `0xdae9`.

**Comment by gaojiaqi7** [comment]
Thanks @dingelish It shouldn't be a hardcoded value. I will submit a fix
