### ISSUE TITLE
staging: compile td-payload generates a warning

### ISSUE THREAD

**Issue by jiangliu** [confidential-containers/td-shim#75]
root@7c4b62794fd1:/tdshim# cargo xbuild --target ./devtools/rustc-targets/x86_64-unknown-none.json -p td-payload --release
WARNING: There is no root package to read the cargo-xbuild config from.
warning: Linking two modules of different data layouts: '' is 'e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128' whereas 'td_payload.35f7730e-cgu.8' is 'e-m:e-i64:64-f80:128-n8:16:32:64-S128'

warning: `td-payload` (bin "td-payload") generated 1 warning
    Finished release [optimized] target(s) in 0.97s

**Comment by gaojiaqi7** [comment]
Fixed by: https://github.com/confidential-containers/td-shim/commit/1efd04e73b82bd24f7eba59d0434e34456c3c4de
