### ISSUE TITLE
Implement shim loader in td-shim-tools

### ISSUE THREAD

**Issue by jiangliu** [confidential-containers/td-shim#81]
We have a linker `td-shim-ld` in the td-shim-tools crate, there should be a loader too.
The loader should take the responsibilities:
1) parse td-shim binary file into sections
2) validate section information
3) enforce present sections follow the td-shim spec

**Comment by jyao1** [comment]
1) Create a `td-shim-loader` library, that could be reused by the VMM
2) Create a `td-shim-checker` tool (consuming `td-shim-loader`), to validate the format of the final binary.

**Comment by jiangliu** [comment]
> 1. Create a `td-shim-loader` library, that could be reused by the VMM
> 2. Create a `td-shim-checker` tool (consuming `td-shim-loader`), to validate the format of the final binary.

Yes, exactly.
It may be included into the td-shim-tools crate.

**Comment by mxu9** [comment]
As discussed with Jiewen, I will take this task and plan to start this work after I finish test-acpi-payload. ETA is ww15.

**Comment by mxu9** [comment]
> parse td-shim binary file into sections
td-shim is of PE format. Here section means the PE section?

**Comment by jyao1** [comment]
It is meta section, not PE section.

**Comment by jyao1** [comment]
done
