### ISSUE TITLE
Relocate the MAILBOX page to be continuous to the ACPI/event log regions

### ISSUE THREAD

**Issue by jiangliu** [confidential-containers/td-shim#82]
The MAILBOX page should be relocated to upper address to be continuous to the ACPI/event log regions, so the lower region could be released.

**Comment by gaojiaqi7** [comment]
Hi @jiangliu , mailbox is located at 0xFF040000 (can be found in build time layout), do you think it is necessary to relocate it to a memory region adjacent to ACPI/event log?

**Comment by jiangliu** [comment]
> Hi @jiangliu , mailbox is located at 0xFF040000 (can be found in build time layout), do you think it is necessary to relocate it to a memory region adjacent to ACPI/event log?

Yes，we could reuse the memory below mailbox/acpi/event log regions once the relocation is done.

**Comment by jyao1** [comment]
Typically, the ideal memory layout is:
+---------------+
| Usable            |
+---------------+
| ACPI Reclaim |
+---------------+
| ACPI NVS       |
+---------------+
| Reserved        |
+---------------+
