### ISSUE TITLE
regression: MSR access cause exception

### ISSUE THREAD

**Issue by xiaoyuxlu** [confidential-containers/td-shim#92]
MSR access will cause VE exception that cause td-shim failure. 

https://github.com/confidential-containers/td-shim/blob/staging/td-shim/src/bin/td-shim/td/tdx.rs

```
fn enable_execute_disable_bit() {
    let mut msr: u64;

    unsafe { msr = asm_read_msr64(0xC0000080) };
    msr |= 0x800;
    unsafe { asm_write_msr64(0xC0000080, msr) };
}
```

According to TDX spec, 
1) the MSR access should be done by VMCALL, instead of MSR instruction.
2) the TDX module will enable NX by default. Not need to use MSR to enable them again.

This code is redundant and shall be removed.

**Comment by jiangliu** [comment]
Close via #91
