### ISSUE TITLE
regression: HLT causes double exception

### ISSUE THREAD

**Issue by xiaoyuxlu** [confidential-containers/td-shim#93]
See code below in exception handle.

https://github.com/confidential-containers/td-shim/blob/staging/td-exception/src/interrupt.rs
```
fn deadloop() {
    // TBD: empty `loop {}` wastes CPU cycles
    #[allow(clippy::empty_loop)]
    loop {
        x86_64::instructions::interrupts::enable();
        x86_64::instructions::hlt();
    }
}
```

According to TDX spec, the HLT access should be done by VMCALL, instead of HLT instruction.

Using HLT directly will cause reentry to exception handle.

**Comment by jiangliu** [comment]
Close via #91
